tradepacks = {
    'Aged Meat': {'Beef': 12, 'Salt': 5, 'Garlic': 15},
    'Bakers Basics': {'Milk': 15, 'Egg': 30, 'Ground Flour': 35},
    'Barbecue Specialty': {'Beef': 10, 'Chicken': 5, 'Coal': 30, 'Honey': 6},
    'Basic Rations': {'Wheat': 15, 'Corn': 10, 'Apple': 10},
    'Berry Basket': {'Strawberry': 30, 'Blueberry': 50, 'Moonberry': 4, 'Sunberry': 8},
    'Brined Shank': {'Shank': 10, 'Salt': 8, 'Pepper': 10},
    'Building Materials': {'Stone': 100, 'Small Log': 22, 'Hide': 10},
    'Butcher\'s Box': {'Chicken': 8, 'Beef': 5, 'Shank': 5, 'Cheese': 1},
    'Campfire Roast': {'Small Log': 22, 'Stone': 130, 'Chicken': 8},
    'Crafting Basics': {'Copper Ore': 40, 'Hide': 10, 'Small Log': 25},
    'Crisp Produce': {'Apple': 10, 'Brocolli': 5, 'Pea': 10, 'Bean': 5},
    'Dairy Delivery': {'Milk': 15, 'Cheese': 1, 'Egg': 30},
    'Exotic Fruits': {'Watermelon': 4, 'Sunberry': 8, 'Moonberry': 5},
    'Fried Chicken': {'Chicken': 12, 'Onion': 10, 'Garlic': 10, 'Ground Flour': 20},
    'Fruit Basket': {'Grape': 20, 'Watermelon': 2, 'Cherry': 5},
    'General Spices': {'Garlic': 15, 'Onion': 15, 'Pepper': 10, 'Salt': 5},
    'Glaceforde Explorers Kit': {'Wool': 10, 'Small Log': 30, 'Coal': 40},
    'Juicers Box': {'Apple': 5, 'Strawberry': 15, 'Cherry': 5, 'Banana': 3},
    'Kabbar\'s Omelets': {'Egg': 30, 'Cheese': 1, 'Pepper': 15},
    'Kindling Kit': {'Small Log': 38, 'Coal': 40, 'Cotton': 10},
    'Margrove Ale Ingredients': {'Wheat': 30, 'Acorn': 3, 'Pumpkin': 2},
    'Noble Delicacies': {'Moonberry': 10, 'Acorn': 2, 'Pepper': 12},
    'Pickled Vegetables': {'Cabbage': 15, 'Carrot': 50, 'Salt': 8},
    'Pie Making Kit': {'Apple': 5, 'Sunberry': 5, 'Cherry': 4, 'Ground Flour': 30},
    'Ravencrest Finest Wears': {'Cotton': 8, 'Wool': 8, 'Hide': 8},
    'Ravencrest Greens': {'Brocolli': 10, 'Pea': 25, 'Cabbage': 15},
    'Rohna Smoked Ham': {'Shank': 5, 'Acorn': 2, 'Pea': 10, 'Salt': 5},
    'Sailor\'s Remedy': {'Carrot': 20, 'Orange': 5, 'Bean': 20},
    'Sajecho Fruit Basket': {'Banana': 2, 'Watermelon': 1, 'Orange': 4, 'Grape': 10},
    'Sajecho\'s Spices': {'Salt': 5, 'Orange': 4, 'Onion': 15},
    'Seabreeze Rum': {'Corn': 10, 'Cabbage': 8, 'Banana': 5, 'Blueberry': 30},
    'Settler\'s Rations': {'Wheat': 30, 'Carrot': 35, 'Corn': 10},
    'Slums Provisions': {'Cotton': 10, 'Shank': 8, 'Potato': 80},
    'Sombreshade\'s Pie': {'Pumpkin': 5, 'Milk': 10, 'Ground Flour': 20, 'Honey': 13},
    'Strawberry Cakes': {'Ground Flour': 50, 'Milk': 10, 'Strawberry': 40, 'Honey': 10},
    'Vegetable Stew': {'Brocolli': 5, 'Pumpkin': 5, 'Bean': 25, 'Potato': 40},
    'Winemakers Kit': {'Grape': 40, 'Blueberry': 15, 'Moonberry': 5}
}

tradeposts = [
    'Riverend', 
    'Margrove', 
    'Orca Bay', 
    'Seabreeze', 
    'Tarmire', 
    'Darzuac', 
    'Gilead', 
    'Glaceford', 
    'Ravencrest', 
    'Defiance', 
    'Dras Ashar', 
    "Kari'Vir"
]
